options:
  docker: true

pipelines:
  default:
    - step:
        script:
          - export IMAGE_NAME=bitbucketpipelines/scala-sbt
          - docker build -t $IMAGE_NAME:latest .
          - docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
          - docker push $IMAGE_NAME
  tags:
    '*':
      - step:
          script:
             - export IMAGE_NAME=bitbucketpipelines/scala-sbt
             - docker build -t $IMAGE_NAME:$BITBUCKET_TAG .
             - docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
             - docker push $IMAGE_NAME